language: go

sudo: false

go:
  - 1.4.2
  - tip

services:
  - memcached
  - redis-server

addons:
  apt:
    packages:
      - graphicsmagick

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v golang.org/x/tools/cmd/vet
  - go get -v github.com/golang/lint/golint

install: go get -v -t ./...

script:
  - go test -v -cover ./...
  - gofmt -d .
  - go tool vet .
  - golint ./...
